package holders;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JLabel;

import core.ProgramLogic;

public class Configuration {
	
	public static enum OS { WIN, LINUX, MAC };
	
	public final static int windowInitWidth  = 720;
	public final static int windowInitHeight = 500;
	
	public final static String[] VALID_EXTENSIONS_IMAGE = new String[] { "jpeg", "jpg", "png", "webp" };
	public final static String[] VALID_EXTENSIONS_APP   = new String[] { ".jpg", ".jpeg", ".png", ".gif", ".webp", ".mp4", ".mkv", ".flv", ".avi", ".wmv", ".fid" };
	
	public static final int MAX_RECURTION_DEPTH = 16;
	
	public static final List<TFVAR> VARS_TO_OVERRIDE_IN_CONFIG = new ArrayList<TFVAR>();
	public static final List<TFVAR> VARS_PARAMETERS = new ArrayList<TFVAR>();
	public static final Map<String, TFVAR> VARS_PARAMETERS_MAP = new HashMap<String, TFVAR>();
	
	public static final List<TFVAR> VARS_TO_VIDEO_PROCESSING = new ArrayList<TFVAR>();
	public static final List<TFVAR> VARS_TO_IMAGE_PROCESSING = new ArrayList<TFVAR>();
	public static final List<TFVAR> VARS_TO_APNG_PROCESSING  = new ArrayList<TFVAR>();
	public static final List<TFVAR> VARS_TO_GIF_PROCESSING   = new ArrayList<TFVAR>();
	public static final List<TFVAR> VARS_TO_WPANM_PROCESSING = new ArrayList<TFVAR>();
	
	// TODO: Find (maybe) another way to do it
	public static final JLabel INFOLABELTOOLS = new JLabel("");
	public static final JLabel INFOLABELIMAGE = new JLabel("");
	public static final JLabel INFOLABELANIMS = new JLabel("");

	
	public static ToolOptions OPTIONS;
	
	public static CurrentSessionFilesProcessingSettings SETTINGS;
	
	public static boolean PROCESSING = false;
	
	public static final OS os = ProgramLogic.getOperetionSystemType();
	
	// files names
	/** Ending of temporally stored extracted audio file, from source video. */
	public static final String TEMP_AUDIO_END_FILE_NAME_EXTRACT   = "_00_audio.m4a";
	
	/** Ending of temporally stored video file, with packed frames after AI processing, before final scaling. */
	public static final String TEMP_VIDEO_END_FILE_NAME_PACKED    = "_01_enchanced";
	
	/** Ending of temporally stored video file, after scaling. */
	public static final String TEMP_VIDEO_END_FILE_NAME_SCALED    = "_02_scaled";
	
	/** Ending of temporally stored video file, if using some motion stabilization. */
	public static final String TEMP_VIDEO_END_FILE_NAME_DESHAKED  = "_03_deshaked";
	
	// folders names
	/** Name of temporally folder for source frames, extracted from source video file. */
	public static final String TEMP_FRAMES_FOLDER_NAME_SOURCE       = "frames_source";
	
	/** Name of temporally folder for generated by AI interpolated frames, 
	 *  which will used to increase FPS of final video file. */
	public static final String TEMP_FRAMES_FOLDER_NAME_INTERPOLATED = "frames_interpolate";
	
	/** Name of temporally folder for up-scaled frames by AI. */
	public static final String TEMP_FRAMES_FOLDER_NAME_UPSCALED     = "frames_upscale";
	
	// Pathes
	public static final String DEFAULT_PATH_ALL_TEMP_FILES_LOCATION = "./uitooltemp";
	
	/** Global configuration file path for entire Tool. */
	public static final String CORE_CONFIG_FILE_NAME = "iutool_settings.conf";
	public static final String CORE_CONFIG_FILE_PATH = ("./" + CORE_CONFIG_FILE_NAME);
	
	/** Files processing configuration file for user chosen file processing preferences (optional). */
	public static final String SESSION_CONFIG_FILE_NAME = "session_settings.conf";
	public static final String SESSION_CONFIG_FILE_PATH = ("./" + SESSION_CONFIG_FILE_NAME);
	
	/** Predefined folder path for temporally storing files. */
	public static final String DEFAULT_TEMP_FILES_FOLDER_LOCATION = "./tempuitoolfiles";
	
	/** Predefined Number of Threads for Image scaling. */
	public static final int DEFAULT_THREADS_NUMBER_FOR_IMAGE_SCALING = 8;
	
	/** Array of ignored Variables names from program config
    on back-propagation check stage. */
	public static final String[] VARIABLES_IGNORE_ARRAY = new String[] {
			"FFMPEG_EXEC_FILE_PATH",
			"UPSCALER_AI_APP_PATH",
			"INTERPOLATION_AI_APP_PATH",
			"TEMP_FILES_FOLDER",
			"OUTPUT_VIDEO_FILE_FPS",
			
			"FRAMES_EXTENSION",
			"SOURCE_VIDEO_FILENAME",
			"SOURCE_VIDEO_FILE_FPS",
			"VIDEO_SCALING_VALUE",
			"CURRENT_STAGE_INPUT_VIDEO_FILE_PATH",
			"CURRENT_STAGE_OUTPUT_VIDEO_FILE_PATH",
			"CURRENT_STAGE_INPUT_FRAMES_FILES_LOCATION_PATH",
			"CURRENT_STAGE_OUTPUT_FRAMES_FILES_LOCATION_PATH",
			"UPSCALER_AI_SCALE_FACTOR",
			
			"IMAGE_PROCESSING_STAGE_UPSCALING",
	};
	
	/** HAshMap of default values for core variables */
	public static final Map<String, String> DEAFULT_CORE_VARIABLES_VALUES_MAP = new HashMap<String, String>();
	
	/** Initialization of Configuration class, for advanced structures */
	public static boolean init() {
		// default values for possibly wrong provided variables
		DEAFULT_CORE_VARIABLES_VALUES_MAP.put("VIDEO_ENCODE_LIB","-c:v libx265 -vtag hvc1 -pix_fmt yuv420p -preset veryslow");
		DEAFULT_CORE_VARIABLES_VALUES_MAP.put("TEMP_FILES_FOLDER","./tempuitoolfiles");
		DEAFULT_CORE_VARIABLES_VALUES_MAP.put("FFMPEG_EXEC_FILE_PATH",">>>PLEASE_PUT_PATH_TO_EXECUTABLE_OF_FFMPEG_PROGRAM_HERE<<<");
		DEAFULT_CORE_VARIABLES_VALUES_MAP.put("UPSCALER_AI_APP_PATH","PATH_TO_UPSCALER_APP_GOES_HERE");
		DEAFULT_CORE_VARIABLES_VALUES_MAP.put("INTERPOLATION_AI_APP_PATH","PATH_TO_INTERPOLATION_AI_MODEL_GOES_HERE");
		DEAFULT_CORE_VARIABLES_VALUES_MAP.put("FRAMES_EXTENSION","jpg");
		DEAFULT_CORE_VARIABLES_VALUES_MAP.put("FRAMES_STORING_FORMAT","frame%08d.$FRAMES_EXTENSION$");
		return true;
	}
	
	public static TFVAR getVAR(String varName) {
		return VARS_PARAMETERS_MAP.get(varName.replace("$", ""));
	}

}
